[package]
name = "koukoku-chat-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.21.7"
webpki = "0.22.1"
webpki-roots = "0.25.2"
